# environment.yml
name: ml_env
channels:
  - conda-forge
dependencies:
  - python=3.9         # pick your version
  - scikit-learn
  - pandas
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - nltk
  - spacy
  - gensim
  - pip
  - pip:
    - sentence-transformers
    - transformers
